export default {
    SET_ALL_VACATIONS: 'SET_ALL_VACATIONS',
    USER_LOGIN: 'USER_LOGIN_ACTION',
    USER_LOGOUT: 'USER_LOGOUT_ACTION',
    UPDATE_FOLLOW: 'UPDATE_FOLLOW_ACTION',
    UPDATE_VACATION: 'UPDATE_VACATION_ACTION',
}
